export const projects = [
	{
		date: 'Aug 2021',
		status: 'Development',
		projectTitle: 'Archive',
		projectDescription: 'SaaS web app that will work as a headless CMS.',
		stack: [
			'Node',
			'JavaScript',
			'Express',
			'Vite',
			'React',
			'TypeScript',
			'Axios',
			'SWR',
			'Windicss',
			'Deta Base',
			'Deta Micros',
		],
		goToLink: 'https://github.com/M4rteaga/react-archive',
	},
	{
		date: 'Sep 2021',
		status: 'Development',
		projectTitle: 'This Portfolio',
		projectDescription: 'Exacltly this portafolio that you are seeing.',
		stack: ['Vite', 'React', 'TypeScript', 'Windicss', 'Mdx'],
		goToLink: 'https://github.com/M4rteaga/myPortfolio',
	},
	{
		date: 'Mar 2021',
		status: 'Done',
		projectTitle: 'Vite Portfolio',
		projectDescription: 'Personal portfolio template with landing page.',
		stack: ['Vite', 'Vue3', 'Typescript', 'Windicss'],
		goToLink: 'https://github.com/M4rteaga/vite-portfolio',
	},
	{
		date: 'Aug 2020',
		status: 'Done',
		projectTitle: 'Viva Air',
		projectDescription:
			'Client part for a college project in which we create a full-stack web app.',
		stack: [
			'Next',
			'React',
			'JavaScript',
			'Tailwindcss',
			'Aws Amplify',
			'Lambda',
			'Aws AKS',
			'Aws RDS',
		],
		goToLink: 'https://github.com/M4rteaga/viva-air',
	},
];
